title: François Vercellotti
email: francoisvercellotti@gmail.com
description: "Mon portfolio personnel, mettant en avant mes projets et mon expérience."
url: "http://localhost:4000"
github_username: "François VERCELLOTTI"

theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed


collections:
  projects:
    output: true  # Cela permet à chaque projet d'être accessible via son URL

# Navigation Links
navigation:
  - title: "Pourquoi travailler ensemble ?"
    url: /about/
  - title: "Découvrir mes projets data"
    url: /projects/
