title: Mon Portfolio
email: francoisvercellotti@gmail.com
description: "Mon portfolio personnel, mettant en avant mes projets et mon expérience."
url: "http://localhost:4000"
github_username: "François VERCELLOTTI"

theme: minima
plugins:
  - jekyll-feed

collections:
  projects:
    output: true  # Cela permet à chaque projet d'être accessible via son URL

# Navigation Links
navigation:
 
  - title: "A propos de moi"
    url: /about/
  - title: "Mes Projets"
    url: /projects/
